# Generated by Django 3.1.7 on 2021-03-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
