# Generated by Django 3.1.7 on 2021-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210308_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Custom', 'Custom'), ('Popular', 'Popular')], default='All', max_length=10, null=True),
        ),
    ]
