# Generated by Django 3.1.7 on 2021-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Custom', 'Custom'), ('Public', 'Public'), ('Popular', 'Popular')], default='All', max_length=10, null=True),
        ),
    ]
