# Generated by Django 3.1.7 on 2021-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210309_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('App', 'App'), ('Entree', 'Entree'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast')], default='Entree', max_length=10, null=True),
        ),
    ]
