# Generated by Django 3.1.7 on 2021-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preptime',
            field=models.IntegerField(default=60),
        ),
    ]
