# Generated by Django 3.1.7 on 2021-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_preptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooktemp',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooktime',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='recipe',
            name='units',
            field=models.CharField(default='servings', max_length=255, null=True),
        ),
    ]
