# Generated by Django 3.1.7 on 2021-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210309_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(default='This recipe site is great!', null=True),
        ),
    ]
