# Generated by Django 3.1.7 on 2021-03-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210309_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
    ]
