# Generated by Django 3.1.7 on 2021-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tempscale',
            field=models.CharField(default='Fahrenheit', max_length=255, null=True),
        ),
    ]
