# Generated by Django 3.1.7 on 2021-03-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_tempscale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredientList',
        ),
    ]
