# Generated by Django 3.1.7 on 2021-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210309_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Custom', 'Custom'), ('Public', 'Public'), ('Popular', 'Popular'), ('Favorite', 'Favorite'), ('Pantry', 'Pantry')], default='All', max_length=10, null=True),
        ),
    ]
