# Generated by Django 3.1.7 on 2021-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210310_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientList',
            field=models.TextField(null=True),
        ),
    ]
