# Generated by Django 3.1.7 on 2021-03-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210310_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientList',
            field=models.JSONField(null=True),
        ),
    ]
