# Generated by Django 3.1.7 on 2021-03-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210310_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientList',
            field=models.JSONField(null=True),
        ),
    ]
