# Generated by Django 3.1.7 on 2021-03-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20210311_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientList',
        ),
    ]
