# Generated by Django 3.1.7 on 2021-03-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_recipe_ingredientlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredientList',
            field=models.JSONField(null=True),
        ),
    ]
