# Generated by Django 3.1.7 on 2021-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipe_ingredientlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientList',
            field=models.TextField(null=True),
        ),
    ]
