# Generated by Django 3.1.7 on 2021-03-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20210311_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientList',
            field=models.JSONField(null=True),
        ),
    ]
