# Generated by Django 3.1.7 on 2021-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20210311_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='weightScale',
            field=models.CharField(default='ounces', max_length=255, null=True),
        ),
    ]
