# Generated by Django 3.1.7 on 2021-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipe_weightscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
    ]
