# Generated by Django 3.1.7 on 2021-03-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20210311_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
