# Generated by Django 3.1.7 on 2021-03-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=models.TextField(default='Add stuff and cook', null=True),
        ),
    ]
